### ISSUE TITLE
Let folks change the location/name of the generated file

### ISSUE THREAD

**Issue by kevmoo** [kevmoo/build_version#2]

**Comment by Solido** [comment]
Flutter doesn't have a src directory ...

**Comment by kevmoo** [comment]
> Flutter doesn't have a src directory ...

`lib/src` is VERY common in all Dart packages. Flutter or not. See https://github.com/flutter/plugins/tree/master/packages/cloud_firestore/lib/src for example

> it feels strange to have this 'src' floating nearly empty in the middle of the project.

Usually you want a version for a published package. In that case, you don't want to pollute the `lib` directory with files you don't want users to import.

See https://www.dartlang.org/tools/pub/package-layout#implementation-files

**Comment by cedx** [comment]
It would be a useful addition. I encountered an issue not tie to this package, but that could be resolved if the `version.dart` file was generated in a different location.

See: dart-lang/angular#1707

**Comment by kevmoo** [comment]
Pull Requests welcome!

**Comment by cedx** [comment]
I would like to contribute to this project, but I don't know anything about the `build` system (I've a preference for `grinder`) :cry:

**Comment by kevmoo** [comment]
FYI: grinder is a task runner, not a build system. :-)

**Comment by kevmoo** [comment]
This is blocked by https://github.com/dart-lang/build/issues/683

I think the best path forward would be something like https://github.com/kevmoo/build_version/issues/4

**Comment by lexaknyazev** [comment]
`source_gen` (as in #4) would produce `.g.dart` files, so `buildExtensions` would still be an issue if we want to keep the current behaviour as a default, right?

**Comment by kevmoo** [comment]
Not really.

You could flag some arbitrary `lib/silly/my_version.dart` file and we'd generate `lib/silly/my_version.g.dart`.

**Comment by lexaknyazev** [comment]
Would `buildExtensions` contain both options? Like
```dart
final buildExtensions = const {
    r'$lib$': ['src/version.dart', '.g.dart']
  };

**Comment by kevmoo** [comment]
No, it'd be a separate builder.
