### ISSUE TITLE
Split build name and build number

### ISSUE THREAD

**Issue by mrverdant13** [kevmoo/build_version#23]
## Description

The version often includes a version name and a version number, i.e. `4.2.3+45`.

It would be useful to generate two different constants:

```dart
const buildName = '4.2.3';

const buildNumber = '45';

const packageVersion = '$buildName+$buildNumber';
```

**Comment by kevmoo** [comment]
Likely going to leave it as-is. You can always pop this bit out with `package:pub_semver`
